name: Minecraft Mod CI

on: [push]

jobs:
  build:
    name: "Mod Build"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Get Build Filename
      id: getfilename
      run: echo "::set-output name=file::$(ls build/libs/minecrowdcontrol-*.jar)"
    - name: Upload build
      uses: actions/upload-artifact@v1
      with:
        name: "Minecraft Mod JAR file"
        path: ${{ steps.getfilename.outputs.file }}
    - name: Upload Crowd Control CS file
      uses: actions/upload-artifact@v1
      with:
        name: "Crowd Control Configuration"
        path: "minecrowdcontrol.cs"